defaults:
    - override hydra/launcher: submitit_local

# evaluation
task: mt80
checkpoint: ???
eval_episodes: 10
seed: 1
save_video: false

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: 5
num_enc_layers: 2
enc_dim: 256
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
bin_size: ???
